/**
 * Design System Tokens
 * Generated by /design-tokens skill from Figma variables.
 * Do not edit manually — re-run the skill to update.
 */

// Colors — populated by /design-tokens

// Typography — populated by /design-tokens

// Spacing — populated by /design-tokens

// Border Radius — populated by /design-tokens

// Shadows — populated by /design-tokens
